 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   test:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet restore
       - run: dotnet test tests/RLib.Localization.Tests/RLib.Localization.Tests.csproj
 workflow:
   test:
     jobs:
       - test